[build]
publish = "dist"
command = "yarn build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/services/analytics"
to = "/services/creative"
status = 301
force = true

[[redirects]]
from = "/try-500"
to = "/claim-creative-test-drive"
status = 301
force = true
