name = "blazex-astro"
main = "./dist/_worker.js"
compatibility_date = "2024-12-01"
# Using Node.js runtime features
compatibility_flags = ["nodejs_compat"]

[build]
command = "yarn build"

[assets]
binding = "ASSETS"
directory = "./dist/client"
